version: "3"

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - ./.env
    command: bash -c "python3 /app/manage.py makemigrations
                      && python3 /app/manage.py migrate
                      && python3 /app/manage.py runserver 0.0.0.0:8000"
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    restart: on-failure
    depends_on:
      - db

volumes:
  postgres_data: